###
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyOTIyMDB9.SL8k3Nk4q9Ol9QAqg3hQQJXGQv_NC2bD_-gY7ilqUmA

###
GET http://localhost:3000/products/1.json

###
POST http://localhost:3000/products.json
content-type: application/json
Authorization: Bearer {{jwtnapolean}}

{
  "name": "Eggs: one dozen",
  "price": 4,
  "description": "fried, scrambled, boiled. delicious and nutritious",
  "supplier_id": 2
}

###
PATCH http://localhost:3000/products/8.json
content-type: application/json
Authorization: Bearer {{jwtben}}

{
  "name": "jackfruitsi",
  "price": "11",
  "description": "used by vegetarians for bbq"
}

###
DELETE http://localhost:3000/products/8.json
Authorization: Bearer {{jwtben}}

###
POST http://localhost:3000/suppliers.json
content-type: application/json

{
  "name": "HyVee",
  "email": "Hyvee@Hyvee.com",
  "phone_number": "666-666-6667"
}

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Napolean Bonaparte",
  "email": "complex@napolean.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "@napolean.com",
  "password": "password"
}

### Orders create
POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{jwtnapolean}}

{
  "product_id": 1,
  "quantity": 5
  }

### Orders index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwtnapolean}}

### Orders show
GET http://localhost:3000/orders/15.json
Authorization: Bearer {{jwtnapolean}}

### Image update
PATCH http://localhost:3000/images/5.json
content-type: application/json
Authorization: Bearer {{jwtnapolean}}

{
  "url": "https://www.google.com/imgres?imgurl=https%3A%2F%2Fthumbs.dreamstime.com%2Fb%2Ffresh-green-apple-26821143.jpg&imgrefurl=https%3A%2F%2Fwww.dreamstime.com%2Fphotos-images%2Fgreen-apple.html&tbnid=M5m_hiAFCtinwM&vet=12ahUKEwi_5IjXg-zzAhWjoK0KHaFcBK8QMygGegUIARDRAQ..i&docid=PJztneRzqQ6dfM&w=800&h=533&q=apple%20stock%20photo&ved=2ahUKEwi_5IjXg-zzAhWjoK0KHaFcBK8QMygGegUIARDRAQ"
}


###
@jwtgeorge = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUzNzc2NTV9.7xJ2Ohn9dfr2TVCuqfNhWesNTLEYaF-4steH2hZwCzI

###
@jwtben = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUzODc1MDJ9.CgLSFZVVWlUQBg53cFsVLrTgNa6fi9Ko1qQpmr3Y-3k

###
@jwtnapolean = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2MzU0NzIyNzF9.R5NFr4u1c9qx33edObpyR8HEKhh9wn5zoOTuR7vq3CM