GET http://localhost:3000/products

###
GET http://localhost:3000/products/1.json

###
POST http://localhost:3000/products.json
content-type: application/json

{
  "name": "tomatoee",
  "price": 1,
  "description": "is it really a fruit?",
  "supplier_id": 1
}

###
PATCH http://localhost:3000/products/8.json
content-type: application/json

{
  "name": "jackfruitsi",
  "price": "11",
  "description": "us"
}

###
DELETE http://localhost:3000/products/7.json

###
POST http://localhost:3000/suppliers.json
content-type: application/json

{
  "name": "Target",
  "email": "target@target.com",
  "phone_number": "666-666-6666"
}

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "George Washington",
  "email": "cannottellalie@george.com",
  "password": "password",
  "password_confirmation": "password"
}
