GET http://localhost:3000/products

###
GET http://localhost:3000/products/2.json

###
POST http://localhost:3000/products.json
content-type: application/json

{
  "input_name": "tomato",
  "input_price": "1.0",
  "input_image_url": "alsdkfj",
  "input_description": "is it really a fruit?"
}

###
PATCH http://localhost:3000/products/4.json
content-type: application/json

{
  "name": "jackfruit",
  "price": "5",
  "image_url": "abcdefg",
  "description": "used by vegans for bbq"
}

###
DELETE http://localhost:3000/products/7.json